name: Code coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    
    - name: Install requirements.txt
      run: |
        pip install -r requirements.txt
    
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
        coverage xml -i
        ls -hal
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
